code/sever/Peacock/Peacock.ManageWeb/Areas/Product/Controllers/ProductGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Peacock.Dal;
using Peacock.ViewModel.Manage;
using Peacock.ViewModel.Manage.ProductGroup;

namespace Peacock.ManageWeb.Areas.Product.Controllers
{
    [Authorize]
    [Area("Product")]
    public class ProductGroupController : BaseController
    {
        private readonly ILogger _logger;

        public ProductGroupController(PeacockDbContext peacockDbContext) : base(peacockDbContext)
        {
            //_logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetProductGroup(BaseSearchModel searchModel)
        {
            int count = peacockDbContext.T_Pro_ProductGroup.Where(i => !i.IsDeleted).Count();
            var list = peacockDbContext.T_Pro_ProductGroup.Where(i => !i.IsDeleted).Skip(searchModel.offset).Take(searchModel.limit).ToList();
            return Json(new { total = count, rows = list });
        }

        public ActionResult Edit(int id)
        {
            ProductGroupItem vm = new ProductGroupItem();
            if (id == 0)
                return View(vm);
            var entity = peacockDbContext.T_Pro_ProductGroup
                                         .Include(i => i.LanguageRelationByName).ThenInclude(i => i.TSystemLanguageContent)
                                         .FirstOrDefault(i => i.Id == id);
            if (entity != null)
            {
                vm.Id = entity.Id;
                vm.Code = entity.Code;
                vm.NameZh = entity.LanguageRelationByName.TSystemLanguageContent.FirstOrDefault(i => i.LanguageType == LanguageType.ZhCn)?.DisplayContent;
                vm.NameEn = entity.LanguageRelationByName.TSystemLanguageContent.FirstOrDefault(i => i.LanguageType == LanguageType.En)?.DisplayContent;
                vm.OrderId = entity.OrderId;
            }
            return View(vm);
        }

        [HttpPost]
        public ActionResult Save(ProductGroupItem model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            DateTime dtNow = DateTime.Now;
            bool isCreate = model.Id == 0;
            int id = model.Id;
            T_Pro_ProductGroup entity = new T_Pro_ProductGroup();

            if (isCreate)
            {
                entity.OrderId = model.OrderId;
                entity.Code = model.Code;
                entity.Name = model.NameZh;
                entity.CreatedTime = dtNow;
                entity.CreatedBy = userName;
                entity.LastUpdatedTime = dtNow;
                entity.LastUpdatedBy = userName;
                entity.IsDeleted = false;
                //设置多语言
                T_System_LanguageContent nameZhContent = CreateLanguageContentEntity(model.NameZh, LanguageType.ZhCn);
                T_System_LanguageContent nameEnContent = CreateLanguageContentEntity(model.NameEn, LanguageType.En);

                T_System_LanguageRelation languageRelationEntity = new T_System_LanguageRelation()
                {
                    CreatedBy = userName,
                    CreatedTime = dtNow,
                    LastUpdatedBy = userName,
                    LastUpdatedDate = dtNow,
                    TSystemLanguageContent = new List<T_System_LanguageContent>()
                    {
                        nameZhContent,
                        nameEnContent,
                    }
                };
                entity.LanguageRelationByName = languageRelationEntity;

                peacockDbContext.Add(entity);
            }
            else
            {
                entity = peacockDbContext.T_Pro_ProductGroup.Include(i => i.LanguageRelationByName).ThenInclude(i => i.TSystemLanguageContent)
                                            .FirstOrDefault(i => i.Id == model.Id && !i.IsDeleted);
                if (entity == null)
                {
                    ModelState.AddModelError("Code", "不存在记录，无法更新");
                    return View("Edit", model);
                }

                entity.Code = model.Code;
                entity.Name = model.NameZh;
                entity.OrderId = model.OrderId;
                entity.LastUpdatedTime = dtNow;
                entity.LastUpdatedBy = userName;

                var nameLanguageDict = new Dictionary<string, string>();
                nameLanguageDict.Add(LanguageType.ZhCn, model.NameZh);
                nameLanguageDict.Add(LanguageType.En, model.NameEn);
                entity.LanguageRelationByName = EditLanguageContent(entity.LanguageRelationByName, nameLanguageDict);

                peacockDbContext.Update(entity);
            }
            peacockDbContext.SaveChanges();



            return RedirectToAction("Edit", new { id = entity.Id });
        }

        [HttpPost]
        public ActionResult DeleteByIds(List<int> ids)
        {
            var list = peacockDbContext.T_Pro_ProductGroup.Where(i => ids.Contains(i.Id));
            List<T_Pro_ProductGroup> updateList = new List<T_Pro_ProductGroup>();
            foreach(var item in list)
            {
                if (item.IsDeleted)
                {
                    return Json(Fail("记录已删除，不能重复操作"));
                }
                else
                {
                    item.IsDeleted = true;
                    item.LastUpdatedTime = DateTime.Now;
                    item.LastUpdatedBy = userName;

                    updateList.Add(item);
                }
            }
            if (updateList.Count > 0)
            {
                peacockDbContext.UpdateRange(updateList);
                peacockDbContext.SaveChanges();

                return Json(Success("删除成功"));
            }

            return Json(Fail("删除失败"));
        }
    }
}

code/sever/Peacock/Peacock.ManageWeb/Areas/Product/Views/ProductGroup/Edit.cshtml
@model Peacock.ViewModel.Manage.ProductGroup.ProductGroupItem

<section class="content-header">
    <h1>
        @(Model.Id == 0 ? "新增" : "编辑")商品分组
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="box box-primary">
            <form role="form" method="post" action="@Url.Action("Save", "ProductGroup", new { area = "Product" })">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                @Html.HiddenFor(m => m.Id)

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Code)
                                    @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.OrderId)
                                    @Html.TextBoxFor(m => m.OrderId, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="j-lang-tab">
                                <ul class="nav nav-pills ">
                                    <li class="active">
                                        <a class="nav-link active" href="#tab_zh" data-toggle="tab" aria-expanded="true">中文语言</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#tab_en" data-toggle="tab" aria-expanded="false">英文语言</a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab_zh">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                @Html.LabelFor(m => m.NameZh)
                                                @Html.TextBoxFor(m => m.NameZh, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        @*<div class="col-sm-12">
                                            @Html.LabelFor(m=>m.DescriptionZh)
                                            @Html.TextAreaFor(m => m.DescriptionZh)
                                        </div>*@
                                    </div>
                                    <div class="tab-pane" id="tab_en">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                @Html.LabelFor(m => m.NameEn)
                                                @Html.TextBoxFor(m => m.NameEn, new { @class = "form-control" })
                                            </div>
                                        </div>
                                        @*<div class="col-sm-12">
                                            @Html.LabelFor(m => m.DescriptionEn)
                                            @Html.TextAreaFor(m => m.DescriptionEn)
                                        </div>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row text-danger">
                        @Html.ValidationSummary()
                    </div>
                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">保存</button>
                    <a href="@Url.Action("Index", "ProductGroup", new { area = "Product" })" class="btn btn-default">返回</a>
                </div>
            </form>
        </div>
    </div>
</section>

@*@Html.Partial("_HtmlEditor")*@

@section Scripts {

    <script type="text/javascript">
        $(function () {
            //htmlEditorHelper.Create('#DescriptionZh');
            //htmlEditorHelper.Create('#DescriptionEn');
        });
        
    </script>
}

code/sever/Peacock/Peacock.ManageWeb/Areas/Product/Views/ProductGroup/Index.cshtml
<section class="content-header">
    <h1>商品分组</h1>

    <div class="row">
        <div class="col-sm-4">
            @*<button class="btn btn-success j-btn-add">新增</button>*@
            <a href="/Product/ProductGroup/Edit" class="btn btn-success">新增</a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <table id="table"></table>
        </div>
    </div>
</section>

@Html.Partial("_Confirm")

@section Scripts {

    <script type="text/javascript">

        $(function () {
            let page = new pageHelper();
            page.Init();
            page.bindBtnEvent();
        });

        function pageHelper() { };
        pageHelper.prototype.Init = function () {
            let self = this;
            $('#table').bootstrapTable({
                url: '/Product/ProductGroup/GetProductGroup',
                //url: '/Home/GetDepartment',         //请求后台的URL（*）
                method: 'get',                      //请求方式（*）
                //toolbar: '#toolbar',                //工具按钮用哪个容器
                striped: true,                      //是否显示行间隔色
                cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                pagination: true,                   //是否显示分页（*）
                sortable: true,                     //是否启用排序  列中也有此变量
                sortName: 'Id',                     //定义要排序的列   没定义默认都不排列，同sortOrder结合使用，sortOrder没写的话列默认递增（asc）
                sortOrder: "asc",                   //定义列排序顺序，只能是'asc'或'desc'。
                sortStable: false,                   //如果你把此属性设为了true）我们将为此行添加'_position'属性 （别看错了，是sortStable，sortable在下面）设为true，则和sort部分一样，区别是：在排序过程中，如果存在相等的元素，则原来的顺序不会改变
                queryParams: self.queryParams,//传递参数（*）
                sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
                pageNumber: 1,                       //初始化加载第一页，默认第一页
                pageSize: 10,                       //每页的记录行数（*）
                pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                search: true,                       //是否显示表格搜索
                searchOnEnterKey: true,             //是否输入回车才触发搜索
                strictSearch: true,
                showColumns: true,                  //是否显示所有的列
                showRefresh: true,                  //是否显示刷新按钮
                minimumCountColumns: 2,             //最少允许的列数
                clickToSelect: true,                //是否启用点击选中行
                height: 500,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                uniqueId: "Id",                     //每一行的唯一标识，一般为主键列
                showToggle: true,                    //是否显示详细视图和列表视图的切换按钮
                cardView: false,                    //是否显示详细视图
                detailView: false,                   //是否显示父子表
                columns: [{
                    checkbox: true
                }, {
                    field: 'Name',
                    title: '商品分组名',
                    sortable: true
                }, {
                    field: 'Code',
                    title: '编码',
                    sortable: true
                }, {
                    field: 'OrderId',
                    title: '序号',
                    sortable: true
                }, {
                    field: 'LastUpdatedTime',
                    title: '最后更新时间',
                    sortable: true
                }, {
                    field: 'Id',
                    title: '操作',
                    formatter: self.actionFormatter
                }],
                classes: 'table table-bordered table-hover',
                theadClasses: '',
                onLoadSuccess: function () {
                    self.bindTableActionEvent()
                },
                onLoadError: function () {
                    //showTips("数据加载失败！");
                },
            });
        }

        pageHelper.prototype.queryParams = function (params) {
            var temp = {
                limit: params.limit,
                offset: params.offset,
                order: params.order,
                orderName: params.sort,
                //departmentname: $("#txt_search_departmentname").val(),
                //statu: $("#txt_search_statu").val(),
                search: params.search
            };
            return temp;
        }

        pageHelper.prototype.reload = function () {
            $("#table").bootstrapTable('refresh');
        }

        //操作栏的格式化
        pageHelper.prototype.actionFormatter = function (value, row, index) {
            var id = value;
            var result = "<div class='j-area-action' data-id='" + id + "'>";
            //result += "<a href='javascript:;' class='btn btn-xs green' title='查看' data-action='view'><span class='fa fa-fw fa-eye'></span></a>";
            result += "<a href='javascript:;' class='btn btn-xs blue' title='编辑' data-action='edit'><span class='fa fa-fw fa-edit'></span></a>";
            result += "<a href='javascript:;' class='btn btn-xs red' title='删除' data-action='remove'><span class='fa fa-fw fa-close'></span></a>";
            result += "</div>";
            return result;
        }

        pageHelper.prototype.bindBtnEvent = function () {
            let self = this;

            $('.j-btn-add').on('click', function () {

            });
        }

        pageHelper.prototype.bindTableActionEvent = function () {
            let self = this;

            $('.j-area-action').on('click', function (e) {
                e.preventDefault();
                let $btn = $(e.target).parent('a');
                let $recordId = $btn.parent('.j-area-action').attr('data-id');
                let $action = $btn.attr('data-action');
                if ($action == 'remove') {
                    self.showDeleteConfirm($recordId);
                } else if ($action == 'edit') {
                    window.location.href = '/Product/ProductGroup/Edit?id=' + $recordId;
                } else if ($action == 'view') {
                }
            });
        }

        pageHelper.prototype.showDeleteConfirm = function (id) {
            let self = this;

            peacockConfirm('确定要删除该条记录吗？', function () {
                self.deleteItem(id);
            });
        }

        pageHelper.prototype.deleteItem = function (id) {
            let self = this;

            $.ajax({
                url: '/Product/ProductGroup/DeleteByIds',
                data: { ids: [id] },
                method: 'POST',
                dataType: 'JSON',
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.Success) {
                        window.location.reload();
                    } else {
                        alert("删除失败, " + r.Message);
                        console.log(r);
                    }
                },
                error: function (err) {
                    console.log(err);
                },
                complete: function () {

                }
            });
        }
    </script>
}